#!C:\Users\pandea\OneDrive - University Hospital Southampton NHS Foundation Trust\BitBucket\test_projects\MLOPS-with-ML-FLOW\mlops\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
